import 'package:nexxora/models/call_model.dart';

List<CallModel> cm = [
  CallModel(
    name: "Aldi",
    avatarUrl: "assets/images/miaw.jpg",
    time: "19 april 19:34",
    phone: "08123456789",
    isMissed: false,
    isVideoCall: false,
  ),
  CallModel(
    name: "cung",
    avatarUrl: "assets/images/miaw.jpg",
    time: "19 april 19:34",
    phone: "08123456789",
    isMissed: true,
    isVideoCall: false,
  ),
  CallModel(
    name: "yam",
    avatarUrl: "assets/images/miaw.jpg",
    time: "19 april 19:34",
    phone: "08123456789",
    isMissed: false,
    isVideoCall: true,
  ),
  CallModel(
    name: "Aldi",
    avatarUrl: "assets/images/miaw.jpg",
    time: "19 april 19:34",
    phone: "08123456789",
    isMissed: true,
    isVideoCall: true,
  ),
  CallModel(
    name: "Aldi",
    avatarUrl: "assets/images/miaw.jpg",
    time: "19 april 19:34",
    phone: "08123456789",
    isMissed: false,
    isVideoCall: false,
  ),
  CallModel(
    name: "Aldi",
    avatarUrl: "assets/images/miaw.jpg",
    time: "19 april 19:34",
    phone: "08123456789",
    isMissed: false,
    isVideoCall: false,
  ),
  CallModel(
    name: "Aldi",
    avatarUrl: "assets/images/miaw.jpg",
    time: "19 april 19:34",
    phone: "08123456789",
    isMissed: false,
    isVideoCall: false,
  ),
  CallModel(
    name: "Aldi",
    avatarUrl: "assets/images/miaw.jpg",
    time: "19 april 19:34",
    phone: "08123456789",
    isMissed: false,
    isVideoCall: false,
  ),
  CallModel(
    name: "Aldi",
    avatarUrl: "assets/images/miaw.jpg",
    time: "19 april 19:34",
    phone: "08123456789",
    isMissed: false,
    isVideoCall: false,
  ),
];
