import 'package:nexxora/models/chats_model.dart';

List<ChatsModel> cht = [
  ChatsModel(
    name: "penjual balon 1",
    phone: "0811111111",
    bio: "looooo",
    date: "14/5/26",
    lastMessage: "ayo ml ym",
    time: "17:55",
    avatarUrl: "assets/images/pb1.jpg",
  ),
  ChatsModel(
    name: "penjual balon 2",
    phone: "0811111111",
    bio: "looooo",
    date: "14/5/26",
    lastMessage: "ayo ml yam",
    time: "17:55",
    avatarUrl: "assets/images/pb2.jpg",
  ),
  ChatsModel(
    name: "my mbg gweh",
    phone: "0811111111",
    bio: "looooo",
    date: "5/9/26",
    lastMessage: "ml yammmmmm",
    time: "17:55",
    avatarUrl: "assets/images/myanugweh.jpg",
  ),
  ChatsModel(
    name: "Aldi",
    phone: "0811111111",
    bio: "looooo",
    date: "14/5/26",
    lastMessage: "ayo ml yam",
    time: "17:55",
    avatarUrl: "assets/images/miaw.jpg",
  ),
  ChatsModel(
    name: "letdark",
    phone: "0811111111",
    bio: "looooo",
    date: "14/5/26",
    lastMessage: "ayo ml yam",
    time: "17:55",
    avatarUrl: "assets/images/letdark.jpg",
  ),
  ChatsModel(
    name: "Admin Wa",
    phone: "0811111111",
    bio: "looooo",
    date: "14/5/26",
    lastMessage: "ayo ml yam",
    time: "17:55",
    avatarUrl: "assets/images/wa.jpg",
  ),
  ChatsModel(
    name: "bayu matcha",
    phone: "0811111111",
    bio: "looooo",
    date: "14/5/26",
    lastMessage: "ayo ml yam",
    time: "17:55",
    avatarUrl: "assets/images/mtcha.jpg",
  ),
  ChatsModel(
    name: "Aldi",
    phone: "0811111111",
    bio: "looooo",
    date: "14/5/26",
    lastMessage: "ayo ml yam",
    time: "17:55",
    avatarUrl: "assets/images/miaw.jpg",
  ),
];
